port: 8000

jwt:
  key: "superKey"


email:
  email: "redWhiteGibbonStudio@gmail.com"
  password: "gibbonstudio711259Kk"
  host: "smtp.gmail.com"
  port: ":465"
  companyName: "Gibbon Studio"


keys:
  email_conf_key: "ab2dc433ed5d4a7472c0ad70566e168f924f2f5e907c6afcce7b93a771e0e9f7"

mongo:
  name: "auth"
  uri: "mongodb://0.0.0.0:27017"
  username: "username"
  password: "password"
  users_collection: "users"
  clients_collection: "clients"
